### ISSUE TITLE
Is this collaborative?

### ISSUE THREAD

**Issue by rvosa** [bioboxes/commentary-article#3]
Hi @michaelbarton,

I think the bioboxes initiative is great. At Naturalis we are developing applications that are just complicated enough to be a huge hassle for users to install, so for now we are opting for (Vagrant-managed) virtual machines. 

However, VMs have a big overhead so we are planning to move to docker containers. I strongly agree that a bit of sensible community planning to adopt bioboxes would be a great boon, and so we are planning to make such a move (e.g. https://github.com/naturalis/supersmart/issues/52).

As a watcher of bioboxes on github I noticed you have started a commentary article. I am curious about your intentions with this. Presumably you are looking for community "buy in". Does that also mean that this commentary article is intended to be collaborative with a whole bunch of people signing off on this? I.e. can I help?

Rutger

**Comment by michaelbarton** [comment]
Thanks for your interest Rutger, I will move your comment to bioboxes/rfc#87 because we are already discussing the article there.
